# Generated by Django 4.0.1 on 2022-03-21 18:17

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('main', '0007_rename_question_userresponse_questionnaire_myuser_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='userresponse',
            name='quiz',
        ),
        migrations.AddField(
            model_name='userresponse',
            name='question',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to='main.question'),
        ),
        migrations.AlterField(
            model_name='question',
            name='answers',
            field=models.ManyToManyField(blank=True, to='main.Answer'),
        ),
        migrations.AlterField(
            model_name='questionnaire',
            name='questions',
            field=models.ManyToManyField(blank=True, to='main.Question'),
        ),
        migrations.AlterField(
            model_name='userresponse',
            name='questionnaire',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to='main.questionnaire'),
        ),
        migrations.AlterField(
            model_name='userresponse',
            name='user',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to=settings.AUTH_USER_MODEL),
        ),
        migrations.DeleteModel(
            name='MyUser',
        ),
    ]
