# Generated by Django 4.0.1 on 2022-03-21 18:47

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0008_remove_userresponse_quiz_userresponse_question_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='question',
            name='multiple_choice',
            field=models.BooleanField(default=False, null=True),
        ),
    ]
