# Generated by Django 4.0.1 on 2022-03-21 19:52

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0009_question_multiple_choice'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='userresponse',
            name='answer',
        ),
        migrations.AddField(
            model_name='userresponse',
            name='answers',
            field=models.ManyToManyField(blank=True, to='main.Answer'),
        ),
    ]
