# Generated by Django 4.0.3 on 2022-04-01 23:27

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0010_remove_userresponse_answer_userresponse_answers'),
    ]

    operations = [
        migrations.AddField(
            model_name='questionnaire',
            name='publicResults',
            field=models.BooleanField(blank=True, null=True),
        ),
    ]
