# Generated by Django 4.0.3 on 2022-04-02 09:47

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0011_questionnaire_publicresults'),
    ]

    operations = [
        migrations.AddField(
            model_name='question',
            name='plot',
            field=models.CharField(blank=True, max_length=1500, null=True),
        ),
    ]
