# Generated by Django 4.0.3 on 2022-04-24 19:27

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0014_alter_question_multiple_choice'),
    ]

    operations = [
        migrations.AddField(
            model_name='question',
            name='date',
            field=models.DateField(auto_created=True, null=True),
        ),
    ]
