# Generated by Django 4.0.3 on 2022-04-24 19:44

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0015_question_date'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='question',
            name='date',
        ),
        migrations.AddField(
            model_name='questionnaire',
            name='date',
            field=models.DateField(auto_created=True, null=True),
        ),
    ]
