# Generated by Django 4.0.3 on 2022-05-08 20:51

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0016_remove_question_date_questionnaire_date'),
    ]

    operations = [
        migrations.AddField(
            model_name='questionnaire',
            name='active',
            field=models.BooleanField(default=True, null=True),
        ),
    ]
