# Generated by Django 4.0.3 on 2022-05-13 12:02

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0018_questionnairesdone'),
    ]

    operations = [
        migrations.AlterField(
            model_name='answer',
            name='text',
            field=models.CharField(max_length=80),
        ),
        migrations.AlterField(
            model_name='question',
            name='text',
            field=models.CharField(max_length=80),
        ),
        migrations.AlterField(
            model_name='questionnaire',
            name='text',
            field=models.CharField(max_length=50),
        ),
    ]
